---
- hosts: hw1
  become: true
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  tasks:
    - name: get apache 
      apt:
        name: apache2
        state: latest
        update_cache: true
      become: true
    - name: clone git
      git: 
        repo: https://github.com/ericxyh/CSE356.git
        dest: /var/www/html/hw1
        version: master
    - name: move html
      copy:
        remote_src: true
        src: /var/www/html/hw1/hw0.html
        dest: /var/www/html/hw0.html
